# Generated by Django 2.2.3 on 2019-08-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='value',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
